### ISSUE TITLE
Possibly unpublish on npm?

### ISSUE THREAD

**Issue by PassTheMayo** [dbmeads/fsdb#1]
Hello, dbmeads. This package was last updated over 5 years ago, and I was wondering if you could potentially unpublish it on npm? I have a great idea for this name of a project, and would work great if I could have the `fsdb` name. Since you haven't commited to this in 5 years, I'm assuming you don't have any intentions of continuing it. Thank you.

**Comment by RubenVerg** [comment]
3 years later, is that project still going? I'd love the name as well.
